#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 10/16/2017 6:28 PM
# Generated By: pravi
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$btn_WebPages = New-Object System.Windows.Forms.Button
$btn_ActiveDir = New-Object System.Windows.Forms.Button
$label1 = New-Object System.Windows.Forms.Label
$btn_LaunchApps = New-Object System.Windows.Forms.Button
$btn_RebootMachihne = New-Object System.Windows.Forms.Button
$btn_NetworkShares = New-Object System.Windows.Forms.Button
$btn_NetworkTools = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$btn_RebootMachihne_OnClick= 
{
#TODO: Place custom script here

}

$btn_NetworkTools_OnClick= 
{
#TODO: Place custom script here

}

$btn_LaunchApps_OnClick= 
{
#TODO: Place custom script here

}

$btn_NetworkShares_OnClick= 
{
#TODO: Place custom script here

}

$btn_WebPages_OnClick= 
{
#TODO: Place custom script here

}

$btn_ActiveDir_OnClick= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 437
$System_Drawing_Size.Width = 322
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Blue Prism Main Menu"


$btn_WebPages.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 40
$System_Drawing_Point.Y = 349
$btn_WebPages.Location = $System_Drawing_Point
$btn_WebPages.Name = "btn_WebPages"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 131
$btn_WebPages.Size = $System_Drawing_Size
$btn_WebPages.TabIndex = 6
$btn_WebPages.Text = "Web Pages"
$btn_WebPages.UseVisualStyleBackColor = $True
$btn_WebPages.add_Click($btn_WebPages_OnClick)

$form1.Controls.Add($btn_WebPages)


$btn_ActiveDir.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 40
$System_Drawing_Point.Y = 297
$btn_ActiveDir.Location = $System_Drawing_Point
$btn_ActiveDir.Name = "btn_ActiveDir"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 131
$btn_ActiveDir.Size = $System_Drawing_Size
$btn_ActiveDir.TabIndex = 5
$btn_ActiveDir.Text = "Active Directory"
$btn_ActiveDir.UseVisualStyleBackColor = $True
$btn_ActiveDir.add_Click($btn_ActiveDir_OnClick)

$form1.Controls.Add($btn_ActiveDir)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 30
$System_Drawing_Point.Y = 19
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 48
$System_Drawing_Size.Width = 177
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 4
$label1.Text = "Blue Prism Administration Tools"

$form1.Controls.Add($label1)


$btn_LaunchApps.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 40
$System_Drawing_Point.Y = 246
$btn_LaunchApps.Location = $System_Drawing_Point
$btn_LaunchApps.Name = "btn_LaunchApps"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 131
$btn_LaunchApps.Size = $System_Drawing_Size
$btn_LaunchApps.TabIndex = 3
$btn_LaunchApps.Text = "Launch Apps"
$btn_LaunchApps.UseVisualStyleBackColor = $True
$btn_LaunchApps.add_Click($btn_LaunchApps_OnClick)

$form1.Controls.Add($btn_LaunchApps)


$btn_RebootMachihne.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 40
$System_Drawing_Point.Y = 134
$btn_RebootMachihne.Location = $System_Drawing_Point
$btn_RebootMachihne.Name = "btn_RebootMachihne"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 131
$btn_RebootMachihne.Size = $System_Drawing_Size
$btn_RebootMachihne.TabIndex = 2
$btn_RebootMachihne.Text = "Reboot Machines"
$btn_RebootMachihne.UseVisualStyleBackColor = $True
$btn_RebootMachihne.add_Click($btn_RebootMachihne_OnClick)

$form1.Controls.Add($btn_RebootMachihne)


$btn_NetworkShares.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 40
$System_Drawing_Point.Y = 185
$btn_NetworkShares.Location = $System_Drawing_Point
$btn_NetworkShares.Name = "btn_NetworkShares"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 131
$btn_NetworkShares.Size = $System_Drawing_Size
$btn_NetworkShares.TabIndex = 1
$btn_NetworkShares.Text = "Network shares"
$btn_NetworkShares.UseVisualStyleBackColor = $True
$btn_NetworkShares.add_Click($btn_NetworkShares_OnClick)

$form1.Controls.Add($btn_NetworkShares)


$btn_NetworkTools.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 40
$System_Drawing_Point.Y = 91
$btn_NetworkTools.Location = $System_Drawing_Point
$btn_NetworkTools.Name = "btn_NetworkTools"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 131
$btn_NetworkTools.Size = $System_Drawing_Size
$btn_NetworkTools.TabIndex = 0
$btn_NetworkTools.Text = "Network Tools"
$btn_NetworkTools.UseVisualStyleBackColor = $True
$btn_NetworkTools.add_Click($btn_NetworkTools_OnClick)

$form1.Controls.Add($btn_NetworkTools)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
