#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 10/14/2017 5:16 PM
# Generated By: 
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$textBox1 = New-Object System.Windows.Forms.TextBox
$listBox1 = New-Object System.Windows.Forms.ListBox
$button1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$button1_OnClick= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 444
$System_Drawing_Size.Width = 769
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Primal Form"

[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")
[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")

[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")

[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")

[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")

[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")

[void] $listBox1.Items.Add("atl-dc-001")
[void] $listBox1.Items.Add("atl-dc-002")
[void] $listBox1.Items.Add("atl-dc-003")
[void] $listBox1.Items.Add("atl-dc-004")
[void] $listBox1.Items.Add("atl-dc-005")
[void] $listBox1.Items.Add("atl-dc-006")
[void] $listBox1.Items.Add("atl-dc-007")



$textBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 248
$System_Drawing_Point.Y = 23
$textBox1.Location = $System_Drawing_Point
$textBox1.Multiline = $True
$textBox1.Name = "textBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 251
$System_Drawing_Size.Width = 442
$textBox1.Size = $System_Drawing_Size
$textBox1.TabIndex = 2

$form1.Controls.Add($textBox1)

$listBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$listBox1.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 27
$System_Drawing_Point.Y = 23
$listBox1.Location = $System_Drawing_Point
$listBox1.Name = "listBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 251
$System_Drawing_Size.Width = 200
$listBox1.Size = $System_Drawing_Size
$listBox1.TabIndex = 1

$form1.Controls.Add($listBox1)


$button1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 136
$System_Drawing_Point.Y = 322
$button1.Location = $System_Drawing_Point
$button1.Name = "button1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 48
$System_Drawing_Size.Width = 203
$button1.Size = $System_Drawing_Size
$button1.TabIndex = 0
$button1.Text = "button1"
$button1.UseVisualStyleBackColor = $True
$button1.add_Click($button1_OnClick)

$form1.Controls.Add($button1)

#Add Button event 
    $button1.Add_Click(
        {    

        $selectedVal = $listBox1.SelectedItem
        $pingServer = ping "www.google.com" -n 10 | out-string
        $textBox1.Text = $pingServer

        }
    )



#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
